-- 20260917120000_fix_gating_bypass.sql
--
-- Closes a hole in 20260915120000_wayfinder_feature_gating.sql that let any
-- signed-in account grant itself paid features, permanently.
--
-- The root cause was the same in three places: the database had no idea which
-- objective opens which feature, or what each feature is gated behind. That
-- mapping lived only in src/data/objectives.js and src/data/featureCatalog.js,
-- so every check that needed it was either delegated to the client or skipped.
--
--   unlock_feature()      checked that the objective you named was finished,
--                         but never that it was the objective which opens the
--                         feature you asked for. Finish the easiest objective
--                         once, then claim anything.
--
--   complete_objective()  inserted whatever feature ids arrived in
--                         p_unlock_ids, with no validation whatsoever. This was
--                         the worst of the three: it did not even need a real
--                         objective/feature relationship to exist.
--
--   record_test_attempt() unlocked whatever p_feature_id it was given on a
--                         pass, and the client both grades the test and reports
--                         the score. The one-attempt rule was the only defence,
--                         which is no defence at all when one attempt buys a
--                         permanent grant on a paid feature.
--
-- The fix gives the database the mapping as reference data and re-checks every
-- claim against it. Behaviour for a legitimate user is unchanged: the same
-- objectives open the same features, and the same eight features can be tested
-- out of.
--
-- The three tables below mirror files in the app bundle and are regenerated by
-- scripts/gen-gating-seed.mjs. When those files change, run it and land the
-- output in a NEW migration; the seed replaces each table wholesale, so it is
-- safe to re-run.

-- Wrapped in a transaction so a failure part-way through cannot leave the
-- gate half-rebuilt — old functions with new tables, or vice versa. Postgres
-- DDL is transactional, so this rolls back cleanly.
begin;

-- ─── reference data ──────────────────────────────────────────────────────────
-- Not secret: all three already ship inside the client bundle. They are in the
-- database so the gate checks have something authoritative to test against,
-- not to hide anything.

create table if not exists public.feature_gates (
  feature_id text primary key,
  gate       text not null check (gate in ('open', 'locked', 'paid', 'experimental'))
);

create table if not exists public.objective_unlocks (
  objective_id text not null,
  feature_id   text not null references public.feature_gates(feature_id) on delete cascade,
  primary key (objective_id, feature_id)
);

create table if not exists public.feature_tests (
  feature_id text primary key references public.feature_gates(feature_id) on delete cascade
);

alter table public.feature_gates     enable row level security;
alter table public.objective_unlocks enable row level security;
alter table public.feature_tests     enable row level security;

-- Readable by any signed-in account, writable by none. The app reads its own
-- copy from the bundle; these grants exist so the client can verify what the
-- server actually believes rather than assuming the two agree.
drop policy if exists "feature_gates_read"     on public.feature_gates;
drop policy if exists "objective_unlocks_read" on public.objective_unlocks;
drop policy if exists "feature_tests_read"     on public.feature_tests;

create policy "feature_gates_read"     on public.feature_gates     for select to authenticated using (true);
create policy "objective_unlocks_read" on public.objective_unlocks for select to authenticated using (true);
create policy "feature_tests_read"     on public.feature_tests     for select to authenticated using (true);

-- Generated by scripts/gen-gating-seed.mjs. Do not hand-edit.
-- 27 features, 12 objective->feature unlocks, 8 test banks.

delete from public.feature_gates;
insert into public.feature_gates (feature_id, gate) values
  ('home-desk', 'open'),
  ('training', 'open'),
  ('capture', 'open'),
  ('life-areas', 'open'),
  ('workshop', 'open'),
  ('idea-garden', 'open'),
  ('knowledge-vault', 'open'),
  ('planner', 'open'),
  ('classes', 'open'),
  ('compass', 'open'),
  ('portfolio', 'locked'),
  ('career-map', 'locked'),
  ('weekly-review', 'locked'),
  ('work-mode', 'locked'),
  ('import-hub', 'locked'),
  ('discover', 'locked'),
  ('lesson-builder', 'locked'),
  ('savings-investing', 'locked'),
  ('debt-credit', 'locked'),
  ('labs', 'experimental'),
  ('mentors', 'experimental'),
  ('community-feed', 'experimental'),
  ('fellow-scholars', 'experimental'),
  ('organization', 'paid'),
  ('insights', 'paid'),
  ('ai-import', 'paid'),
  ('custom-paths', 'paid');

delete from public.objective_unlocks;
insert into public.objective_unlocks (objective_id, feature_id) values
  ('hold-the-line', 'weekly-review'),
  ('hold-the-line', 'work-mode'),
  ('ship-first-build', 'portfolio'),
  ('learn-one-skill', 'import-hub'),
  ('learn-one-skill', 'work-mode'),
  ('steady-body', 'weekly-review'),
  ('money-baseline', 'savings-investing'),
  ('money-baseline', 'debt-credit'),
  ('map-your-career', 'career-map'),
  ('clear-the-inbox', 'import-hub'),
  ('show-your-work', 'discover'),
  ('run-one-lesson', 'lesson-builder');

delete from public.feature_tests;
insert into public.feature_tests (feature_id) values
  ('portfolio'),
  ('career-map'),
  ('weekly-review'),
  ('work-mode'),
  ('import-hub'),
  ('lesson-builder'),
  ('savings-investing'),
  ('debt-credit');

-- ─── unlock_feature() — now re-checks the gate AND the mapping ───────────────
--
-- Each method may only ever open the kind of feature it is actually a gate for:
--   'objective'    -> a 'locked' feature, and only one this objective opens
--   'plan'         -> a 'paid' feature, with a live plan
--   'experimental' -> an 'experimental' feature, with the opt-in on
-- An unknown feature id, or an 'open' one (nothing to unlock), is rejected
-- rather than quietly written.

create or replace function public.unlock_feature(
  p_feature_id   text,
  p_method       text,
  p_objective_id text default null
)
returns public.feature_unlocks
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row  public.feature_unlocks;
  v_gate text;
begin
  if auth.uid() is null then
    raise exception 'Not signed in.';
  end if;

  if p_method not in ('objective', 'plan', 'experimental') then
    raise exception 'Unlock method % cannot be claimed from the app.', p_method;
  end if;

  select gate into v_gate from public.feature_gates where feature_id = p_feature_id;

  if v_gate is null then
    raise exception 'There is no feature called %.', p_feature_id;
  end if;

  if v_gate = 'open' then
    raise exception 'Feature % is already open to everyone.', p_feature_id;
  end if;

  if p_method = 'objective' then
    if v_gate <> 'locked' then
      raise exception 'Feature % is behind the % gate, which finishing an objective does not open.', p_feature_id, v_gate;
    end if;
    if p_objective_id is null then
      raise exception 'An objective unlock has to say which objective.';
    end if;
    -- The check that was missing: this objective must be the one that opens
    -- this feature. Finishing any objective used to be enough to claim any.
    if not exists (
      select 1 from public.objective_unlocks
      where objective_id = p_objective_id and feature_id = p_feature_id
    ) then
      raise exception 'Objective % does not open %.', p_objective_id, p_feature_id;
    end if;
    if not exists (
      select 1 from public.user_objectives
      where user_id = auth.uid()
        and objective_id = p_objective_id
        and status = 'completed'
    ) then
      raise exception 'Objective % is not finished yet.', p_objective_id;
    end if;
  end if;

  if p_method = 'plan' then
    if v_gate <> 'paid' then
      raise exception 'Feature % is not a plan feature.', p_feature_id;
    end if;
    if not public.is_plan_active(auth.uid()) then
      raise exception 'That one needs an active plan.';
    end if;
  end if;

  if p_method = 'experimental' then
    if v_gate <> 'experimental' then
      raise exception 'Feature % is not an experimental feature.', p_feature_id;
    end if;
    if not exists (
      select 1 from public.profiles
      where id = auth.uid() and experimental_opt_in = true
    ) then
      raise exception 'Experimental features are switched off for this account.';
    end if;
  end if;

  insert into public.feature_unlocks (user_id, feature_id, method)
  values (auth.uid(), p_feature_id, p_method)
  on conflict (user_id, feature_id) do nothing;

  select * into v_row
  from public.feature_unlocks
  where user_id = auth.uid() and feature_id = p_feature_id;

  return v_row;
end;
$$;

comment on function public.unlock_feature(text, text, text) is
  'Grants a feature after re-checking both the gate it claims to have cleared and, for objective unlocks, that the named objective is the one that opens it.';

grant execute on function public.unlock_feature(text, text, text) to authenticated;

-- ─── complete_objective() — rewards now come from the mapping ────────────────
--
-- p_unlock_ids is kept so the existing client call still type-checks, but it
-- is deliberately IGNORED. What an objective opens is a property of the
-- objective, not something the caller gets a say in.

create or replace function public.complete_objective(
  p_objective_id text,
  p_unlock_ids   text[] default '{}'
)
returns public.user_objectives
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.user_objectives;
begin
  if auth.uid() is null then
    raise exception 'Not signed in.';
  end if;

  update public.user_objectives
     set status = 'completed', completed_at = now()
   where user_id = auth.uid()
     and objective_id = p_objective_id
     and status = 'active'
  returning * into v_row;

  if v_row.id is null then
    raise exception 'No active objective % to complete.', p_objective_id;
  end if;

  -- Whatever this objective actually opens, regardless of what was asked for.
  insert into public.feature_unlocks (user_id, feature_id, method)
  select auth.uid(), ou.feature_id, 'objective'
  from public.objective_unlocks ou
  join public.feature_gates fg on fg.feature_id = ou.feature_id
  where ou.objective_id = p_objective_id
    and fg.gate = 'locked'
  on conflict (user_id, feature_id) do nothing;

  return v_row;
end;
$$;

comment on function public.complete_objective(text, text[]) is
  'Completes the active objective and grants exactly the unlocks the mapping says it carries. p_unlock_ids is ignored and retained only for call compatibility.';

grant execute on function public.complete_objective(text, text[]) to authenticated;

-- ─── record_test_attempt() — only for things that can be tested out of ───────
--
-- Unchanged except for the allowlist check. The client still grades its own
-- test, which is tolerable for a 'locked' feature with one lifetime attempt,
-- and is not tolerable for anything else — so anything else is now refused
-- before an attempt is even recorded.

create or replace function public.record_test_attempt(
  p_feature_id text,
  p_score      int,
  p_total      int,
  p_pass_mark  int
)
returns public.feature_test_attempts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_passed boolean;
  v_row    public.feature_test_attempts;
begin
  if auth.uid() is null then
    raise exception 'Not signed in.';
  end if;

  -- feature_tests only ever contains 'locked' features; the generator refuses
  -- to emit anything else.
  if not exists (select 1 from public.feature_tests where feature_id = p_feature_id) then
    raise exception 'Feature % cannot be tested out of.', p_feature_id;
  end if;

  if p_total <= 0 or p_score < 0 or p_score > p_total then
    raise exception 'Nonsense score: % of %.', p_score, p_total;
  end if;

  if p_pass_mark < ceil(p_total / 2.0) then
    raise exception 'A pass mark of % out of % is not a check.', p_pass_mark, p_total;
  end if;

  if exists (
    select 1 from public.feature_test_attempts
    where user_id = auth.uid() and feature_id = p_feature_id
  ) then
    raise exception 'This test has already been attempted. The objective path is the way in now.';
  end if;

  v_passed := p_score >= p_pass_mark;

  insert into public.feature_test_attempts (user_id, feature_id, passed, score, total)
  values (auth.uid(), p_feature_id, v_passed, p_score, p_total)
  returning * into v_row;

  if v_passed then
    insert into public.feature_unlocks (user_id, feature_id, method)
    values (auth.uid(), p_feature_id, 'test')
    on conflict (user_id, feature_id) do nothing;
  end if;

  return v_row;
end;
$$;

comment on function public.record_test_attempt(text, int, int, int) is
  'Records the single allowed test-out attempt for a testable feature and unlocks it on a pass. Refuses features that are not in feature_tests.';

grant execute on function public.record_test_attempt(text, int, int, int) to authenticated;

-- ─── clean up grants already handed out through the hole ─────────────────────
--
-- Any unlock whose method is 'objective' but which no completed objective of
-- that user actually opens was obtained through the bug. Unlocks earned by
-- 'test', 'plan' or an admin 'granted' are left alone.

delete from public.feature_unlocks fu
where fu.method = 'objective'
  and not exists (
    select 1
    from public.objective_unlocks ou
    join public.user_objectives uo
      on uo.objective_id = ou.objective_id
     and uo.user_id = fu.user_id
     and uo.status = 'completed'
    where ou.feature_id = fu.feature_id
  );

commit;
